---
- name: Install Samba packages
  ansible.builtin.package:
    name: "{{ samba_server_packages }}"
    state: present

- name: Start smb.conf from scratch
  ansible.builtin.copy:
    dest: /etc/samba/smb.conf
    content: "{{ samba_server_trunc_header | comment }}"
    owner: root
    mode: '0444'
  when: samba_server_trunc_conf | bool
  notify:
    - restart samba services

- name: Tune smb.conf (global)
  community.general.ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: root
    mode: '0444'
  loop: "{{ samba_server_conf_global }}"
  notify:
    - restart samba services

- name: Tune smb.conf (homes)
  community.general.ini_file:
    path: /etc/samba/smb.conf
    section: homes
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    allow_no_value: true
    owner: root
    mode: '0444'
  loop: "{{ samba_server_conf_homes }}"
  when: samba_server_homes_enabled | bool
  notify:
    - restart samba services

- name: Tune smb.conf (rest)
  community.general.ini_file:
    path: /etc/samba/smb.conf
    section: "{{ item.0.section }}"
    option: "{{ item.1.option }}"
    value: "{{ item.1.value }}"
    owner: root
    mode: '0444'
  loop: "{{ query('subelements', samba_server_conf_shares, 'options') }}"
  notify:
    - restart samba services

- name: Create Samba users if they don't exist yet
  ansible.builtin.shell: >
    set -o nounset -o pipefail -o errexit &&
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  args:
    executable: /bin/bash
  loop: "{{ samba_server_users }}"
  no_log: true
  register: __create_user
  changed_when: "'Added user' in __create_user.stdout"
